Base/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app import urls as app_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(app_urls)),
]

app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^app/', views.BaseView.as_view(), name='home')
]

app/models.py
from django.db import models
from app.storage import OverwriteStorage


genders = (
    ('UNSPECIFIED', 'SSML_VOICE_GENDER_UNSPECIFIED'),
    ('MALE', 'MALE'),
    ('FEMALE', 'FEMALE'),
    ('NEUTRAL', 'NEUTRAL'),
)

voice_types = (
    ('nl-NL-Standard-A', 'nl-NL-Standard-A'),
    ('en-AU-Standard-A', 'en-AU-Standard-A'),
    ('en-AU-Standard-B', 'en-AU-Standard-B'),
    ('en-AU-Standard-C', 'en-AU-Standard-C'),
    ('en-AU-Standard-D', 'en-AU-Standard-D'),
    ('en-GB-Standard-A', 'en-GB-Standard-A'),
    ('en-GB-Standard-B', 'en-GB-Standard-B'),
    ('en-GB-Standard-C', 'en-GB-Standard-C'),
    ('en-GB-Standard-D', 'en-GB-Standard-D'),
    ('en-US-Wavenet-A', 'en-US-Wavenet-A'),
    ('en-US-Wavenet-B', 'en-US-Wavenet-B'),
    ('en-US-Wavenet-C', 'en-US-Wavenet-C'),
    ('en-US-Wavenet-D', 'en-US-Wavenet-D'),
    ('en-US-Wavenet-E', 'en-US-Wavenet-E'),
    ('en-US-Wavenet-F', 'en-US-Wavenet-F'),
    ('en-US-Standard-B', 'en-US-Standard-B'),
    ('en-US-Standard-C', 'en-US-Standard-C'),
    ('en-US-Standard-D', 'en-US-Standard-D'),
    ('en-US-Standard-E', 'en-US-Standard-E'),
    ('fr-FR-Standard-C', 'fr-FR-Standard-C'),
    ('fr-FR-Standard-D', 'fr-FR-Standard-D'),
    ('fr-CA-Standard-A', 'fr-CA-Standard-A'),
    ('fr-CA-Standard-B', 'fr-CA-Standard-B'),
    ('fr-CA-Standard-C', 'fr-CA-Standard-C'),
    ('fr-CA-Standard-D', 'fr-CA-Standard-D'),
    ('de-DE-Standard-A', 'de-DE-Standard-A'),
    ('de-DE-Standard-B', 'de-DE-Standard-B'),
    ('it-IT-Standard-A', 'it-IT-Standard-A'),
    ('ja-JP-Standard-A', 'ja-JP-Standard-A'),
    ('ko-KR-Standard-A', 'ko-KR-Standard-A'),
    ('pt-BR-Standard-A', 'pt-BR-Standard-A'),
    ('es-ES-Standard-A', 'es-ES-Standard-A'),
    ('sv-SE-Standard-A', 'sv-SE-Standard-A'),
    ('tr-TR-Standard-A', 'tr-TR-Standard-A'),
)

speed = (
    ('0.25', '0.25'),
    ('0.50', '0.50'),
    ('0.75', '0.75'),
    ('1', '1'),
    ('1.25', '1.25'),
    ('1.50', '1.50'),
    ('1.75', '1.55'),
    ('2', '2'),
    ('2.25', '2.25'),
    ('2.50', '2.50'),
    ('2.45', '2.75'),
    ('3', '3'),
    ('3.25', '3.25'),
    ('3.50', '3.50'),
    ('3.75', '3.75'),
    ('4', '4'),
)

pitch = (
    ('-20', '-20'),
    ('-19', '-19'),
    ('-18', '-18'),
    ('-17', '-17'),
    ('-16', '-16'),
    ('-15', '-15'),
    ('-14', '-14'),
    ('-13', '-13'),
    ('-12', '-12'),
    ('-11', '-11'),
    ('-10', '-10'),
    ('-09', '-09'),
    ('-08', '-08'),
    ('-07', '-07'),
    ('-06', '-06'),
    ('-05', '-05'),
    ('-04', '-04'),
    ('-03', '-03'),
    ('-02', '-02'),
    ('-01', '-01'),
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
    ('7', '7'),
    ('8', '8'),
    ('9', '9'),
    ('10', '10'),
    ('11', '11'),
    ('12', '12'),
    ('13', '13'),
    ('14', '14'),
    ('15', '15'),
    ('16', '16'),
    ('17', '17'),
    ('18', '18'),
    ('19', '19'),
    ('20', '20'),
)


class BaseModel(models.Model):
    textFile = models.FileField(storage=OverwriteStorage(), upload_to='texts/', name='textFile')
    gender = models.CharField(max_length=100, choices=genders, name='gender',)
    pitch = models.CharField(max_length=100, name='pitch', choices=pitch,)
    speed = models.CharField(max_length=100, name='speed', choices=speed,)
    voice_type = models.CharField(max_length=100, choices=voice_types, name='voice_type', default='')

app/forms.py
from django import forms

from . import models


class BaseForm(forms.ModelForm):
    class Meta:
        model = models.BaseModel
        fields = ('textFile', 'gender', 'voice_type', 'pitch', 'speed')

app/views.py
import os
import random
import string
from pathlib import Path
from django.shortcuts import render
from django.views.generic import CreateView
from django.http import HttpResponse
from django.http import FileResponse
from google.cloud import texttospeech_v1beta1

from Base import settings
from . import forms
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file('svc_cred.json')


# credentials = GoogleCredentials.get_application_default()


def generate_pid():
    digits = "".join([random.choice(string.digits) for i in range(4)])
    pid = digits
    return pid


def text_to_speech_manager(text_path, pitch, speed, gender, type):
    text = text_path
    txt = Path(text_path).read_text(encoding='cp1252')
    input_text = {'text': txt}
    voice = {
        'language_code': 'en-US',
        'name': type,
        'ssml_gender': gender,
    }
    audio_config = {
        'audio_encoding': texttospeech_v1beta1.enums.AudioEncoding.MP3,
        'pitch': float(pitch),
        # 'speakingRate': speed,
    }
    client = texttospeech_v1beta1.TextToSpeechClient(credentials=credentials)
    response = client.synthesize_speech(input_=input_text,
                                        voice=voice,
                                        audio_config=audio_config)
    with open('media/audios/output.mp3', 'wb') as out:
        out.write(response.audio_content)
        print('Audio content written to file "output.mp3"')

    # dict_response = dict(response)
    response_file = FileResponse('media/audios/output.mp3', content_type='mp3')
    response_file['Content-Disposition'] = 'attachment; filename="output.mp3"'
    return response_file


class BaseView(CreateView):
    def get(self, request, *args, **kwargs):
        form = forms.BaseForm()
        return render(request, 'form.html', {'form': form})

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            post_data = request.POST.copy()
            form = forms.BaseForm(post_data, request.FILES)
            print('get post req')
            print(form.errors)
            if form.is_valid():
                print('form is valid')
                obj = form
                obj.textFile = form.cleaned_data['textFile']
                obj.gender = form.cleaned_data['gender']
                obj.pitch = form.cleaned_data['pitch']
                obj.speed = form.cleaned_data['speed']
                obj.voice_type = form.cleaned_data['voice_type']
                obj.save()
                text_path = os.path.join(settings.MEDIA_ROOT, 'texts/', obj.textFile.name)
                text = text_path
                txt = Path(text).read_text(encoding='cp1252')
                fileName = obj.textFile.name[:-4]
                print('File Name is: {}'.format(fileName))
                input_text = {'text': txt}
                voice = {
                    'language_code': 'en-US',
                    'ssml_gender': obj.gender,
                }
                audio_config = {
                    'audio_encoding': texttospeech_v1beta1.enums.AudioEncoding.MP3,
                    'pitch': float(obj.pitch),
                    'speaking_rate': float(obj.speed),
                }
                client = texttospeech_v1beta1.TextToSpeechClient(credentials=credentials)
                response = client.synthesize_speech(input_=input_text,
                                                    voice=voice,
                                                    audio_config=audio_config)
                with open('media/audios/' + str(fileName) + '.mp3', 'wb') as out:
                    out.write(response.audio_content)
                    print('Audio content written to file "output.mp3"')
                
                file = open('media/audios/' + str(fileName) + '.mp3', "rb").read()
                rea_response = HttpResponse(file, content_type='audio/mpeg')
                rea_response['Content-Disposition'] = 'attachment; filename={}'.format(fileName + '.mp3')

                return rea_response
            else:
                return HttpResponse('Something went wrong', status=400)

templates/form.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Google Text Analysis</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/spinner.css' %}"/>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <br>
    <h2 class="aligned">Give voice to your text by using the power of Google's Text-to-Speech API: </h2>
    <form id="fileForm" class="form-horizontal" action="{% url 'home' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <br/>
            <div class="form-group">
                <label for="textFile">Text File: </label>
                <br/>
                <input type="file" name="textFile" id="textFile">
            </div>
        </div>
        <div class="form-row">
            <br/>
            <div class="form-group">
                <label for="gender">Voice Gender</label>
                <select class="form-control" name="gender" id="gender">
                    <option value="SSML_VOICE_GENDER_UNSPECIFIED">UNSPECIFIED</option>
                    <option value="MALE">MALE</option>
                    <option value="FEMALE">FEMALE</option>
                    <option value="NEUTRAL">NEUTRAL</option>
                </select>
            </div>
            <div class="form-group" style="margin-left: 5%">
                <label for="voice_type">Voice Type:</label>
                <select class="form-control" id="voice_type" name="voice_type">
                    <option value="nl-NL-Standard-A">nl-NL-Standard-A</option>
                    <option value="en-AU-Standard-A">en-AU-Standard-A</option>
                    <option value="en-AU-Standard-B">en-AU-Standard-B</option>
                    <option value="en-AU-Standard-C">en-AU-Standard-C</option>
                    <option value="en-AU-Standard-D">en-AU-Standard-D</option>
                    <option value="en-GB-Standard-A">en-GB-Standard-A</option>
                    <option value="en-GB-Standard-B">en-GB-Standard-B</option>
                    <option value="en-GB-Standard-C">en-GB-Standard-C</option>
                    <option value="en-GB-Standard-D">en-GB-Standard-D</option>
                    <option value="en-US-Wavenet-A">en-US-Wavenet-A</option>
                    <option value="en-US-Wavenet-B">en-US-Wavenet-B</option>
                    <option value="en-US-Wavenet-C">en-US-Wavenet-C</option>
                    <option value="en-US-Wavenet-D">en-US-Wavenet-D</option>
                    <option value="en-US-Wavenet-E">en-US-Wavenet-E</option>
                    <option value="en-US-Wavenet-F">en-US-Wavenet-F</option>
                    <option value="en-US-Standard-B">en-US-Standard-B</option>
                    <option value="en-US-Standard-C">en-US-Standard-C</option>
                    <option value="en-US-Standard-D">en-US-Standard-D</option>
                    <option value="en-US-Standard-E">en-US-Standard-E</option>
                    <option value="fr-FR-Standard-C">fr-FR-Standard-C</option>
                    <option value="fr-FR-Standard-D">fr-FR-Standard-D</option>
                    <option value="fr-CA-Standard-A">fr-CA-Standard-A</option>
                    <option value="fr-CA-Standard-B">fr-CA-Standard-B</option>
                    <option value="fr-CA-Standard-C">fr-CA-Standard-C</option>
                    <option value="fr-CA-Standard-D">fr-CA-Standard-D</option>
                    <option value="de-DE-Standard-A">de-DE-Standard-A</option>
                    <option value="de-DE-Standard-B">de-DE-Standard-B</option>
                    <option value="it-IT-Standard-A">it-IT-Standard-A</option>
                    <option value="ja-JP-Standard-A">ja-JP-Standard-A</option>
                    <option value="ko-KR-Standard-A">ko-KR-Standard-A</option>
                    <option value="pt-BR-Standard-A">pt-BR-Standard-A</option>
                    <option value="es-ES-Standard-A">es-ES-Standard-A</option>
                    <option value="sv-SE-Standard-A">sv-SE-Standard-A</option>
                    <option value="tr-TR-Standard-A">tr-TR-Standard-A</option>
                </select>
            </div>
            <div class="form-group" style="margin-left: 5%">
                <label for="pitch">Pitch Range: </label>
                <select name="pitch" class="form-control" title="" required="" id="id_pitch">
                    <option value="" selected="">---------</option>

                    <option value="-20">-20</option>

                    <option value="-19">-19</option>

                    <option value="-18">-18</option>

                    <option value="-17">-17</option>

                    <option value="-16">-16</option>

                    <option value="-15">-15</option>

                    <option value="-14">-14</option>

                    <option value="-13">-13</option>

                    <option value="-12">-12</option>

                    <option value="-11">-11</option>

                    <option value="-10">-10</option>

                    <option value="-09">-09</option>

                    <option value="-08">-08</option>

                    <option value="-07">-07</option>

                    <option value="-06">-06</option>

                    <option value="-05">-05</option>

                    <option value="-04">-04</option>

                    <option value="-03">-03</option>

                    <option value="-02">-02</option>

                    <option value="-01">-01</option>

                    <option value="1">1</option>

                    <option value="2">2</option>

                    <option value="3">3</option>

                    <option value="4">4</option>

                    <option value="5">5</option>

                    <option value="6">6</option>

                    <option value="7">7</option>

                    <option value="8">8</option>

                    <option value="9">9</option>

                    <option value="10">10</option>

                    <option value="11">11</option>

                    <option value="12">12</option>

                    <option value="13">13</option>

                    <option value="14">14</option>

                    <option value="15">15</option>

                    <option value="16">16</option>

                    <option value="17">17</option>

                    <option value="18">18</option>

                    <option value="19">19</option>

                    <option value="20">20</option>
                </select>
            </div>
            <div class="form-group" style="margin-left: 5%">
                <label for="speed">Speed Range: </label>
                <select name="speed" class="form-control" title="" required="" id="id_speed">
                    <option value="" selected="">---------</option>

                    <option value="0.25">0.25</option>

                    <option value="0.50">0.50</option>

                    <option value="0.75">0.75</option>

                    <option value="1">1</option>

                    <option value="1.25">1.25</option>

                    <option value="1.50">1.50</option>

                    <option value="1.75">1.55</option>

                    <option value="2">2</option>

                    <option value="2.25">2.25</option>

                    <option value="2.50">2.50</option>

                    <option value="2.45">2.75</option>

                    <option value="3">3</option>

                    <option value="3.25">3.25</option>

                    <option value="3.50">3.50</option>

                    <option value="3.75">3.75</option>

                    <option value="4">4</option>

                </select>
            </div>
        </div>
        <br>
        <button type="submit" class="btn btn-lg btn-primary">Generate Audio</button>
    </form>
    <br/>
    <div class="alert alert-success" id="success" role="alert" hidden>
        Your voice has been generated successfully!
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>
</body>
</html>